# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mainUrl: '%env(string:MAIN_URL)%'
    s3:
        endpoint: '%env(string:S3_ENDPOINT)%'
        key: '%env(string:S3_KEY)%'
        secret: '%env(string:S3_SECRET)%'
        bucket: '%env(string:S3_BUCKET)%'
        region: '%env(string:S3_REGION)%'
    security:
        token: '%env(string:SECURE_TOKEN)%'

    public_s3_host: '%env(string:PUBLIC_S3_HOST)%'
    admin_key: '%env(string:ADMIN_KEY)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
#            - '../src/Infrastructure/Http/DTO/**'
            - '../src/Kernel.php'
    App\Infrastructure\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
